### ISSUE TITLE
parallax 

### ISSUE THREAD

**Issue by vivkay** [vivkay/push-page-navigation#2]
Hi @thomasjbradley, 

I'm trying to add css parallax on this site using your tutorial here: https://www.youtube.com/watch?v=n9zLJ0I8Djk 

I get stuck when adding the transform:translateZ property (-1px). Nothing seems to happen. 

I'm not sure if there are other elements on the body interfering with this property? (I'm adding this to our push-navigation exercise, but am not sure where to look for potential conflicts). 

Here's what I have added for the parallax:

```
html {
    box-sizing: border-box;
    -moz-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
    text-size-adjust: 100%;
  overflow: hidden;
}

*, *:before, *:after {
    box-sizing: inherit;
}

body{
  font-family: sans-serif;
  @include zero;
  // Hides close button if there is no js
  &.noscript .close-btn,
  &.noscript .toggle-btn{
      display: none;
  }
  height: 100vh;
  margin: 0;
  overflow-y: auto;
  overflow-x: hidden;
  -webkit-overflow-scrolling: touch;

  -webkit-perspective: 1px;
  perspective: 1px;
}

.parallax-group {
  -webkit-transform-style: preserve-3d;
  transform-style: preserve-3d;
}

.parallax-back {
  width: 100%;
  transform: translateZ(-1px);
}

```

and the corresponding HTML is:

```
          <div class="parallax-group">
            <img class="parallax-back" src="img/billboard.jpg" alt="">
            <h1 class="parallax-front">We act to conserve threatened species and ecosystems worldwide</h1>
          </div>
```

Would you recommend a javascript parallax technique instead, or am I missing something on this one?

Thanks SO much!

Viv

**Comment by thomasjbradley** [comment]
I think it’s because of the `.site-wrapper`, `.sliding-canvas` and `.header`. I believe the `.parallax-group` must be directly inside the `<body>`.

In this situation, maybe JS parallax would work better for you.

**Comment by vivkay** [comment]
Ok, thank you @thomasjbradley !
